"""m3_p0_refactor_shift_rule_grid

Revision ID: 83ed9fe9409e
Revises: e3f4a5b6c7d8
Create Date: 2026-07-13 10:39:17.537094
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '83ed9fe9409e'
down_revision: str | None = 'e3f4a5b6c7d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_rule_version',
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('persons_per_cell', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['shift_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_no', name='uq_shift_rule_version')
    )
    op.drop_index(op.f('ix_holiday_calendar_year'), table_name='holiday_calendar')
    op.add_column('monthly_schedule', sa.Column('rule_version_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('uq_monthly_schedule_org_month'), table_name='monthly_schedule', postgresql_where='(deleted_at IS NULL)')
    op.create_index('uq_monthly_schedule_org', 'monthly_schedule', ['org_unit_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key(None, 'monthly_schedule', 'shift_rule_version', ['rule_version_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('monthly_schedule', 'year_month')
    op.drop_column('person', 'rotation_order')
    op.drop_index(op.f('ix_schedule_day_schedule_id'), table_name='schedule_day')
    op.add_column('shift_rule', sa.Column('cycle_days', sa.Integer(), nullable=False))
    op.add_column('shift_rule', sa.Column('start_date', sa.String(length=10), nullable=False))
    op.add_column('shift_rule', sa.Column('persons_per_cell', sa.Integer(), nullable=False))
    op.drop_column('shift_rule', 'persons_per_shift')
    op.drop_column('shift_rule', 'rule_type')
    op.drop_column('shift_rule', 'station_type')
    op.add_column('shift_rule_item', sa.Column('version_id', sa.BigInteger(), nullable=False))
    op.add_column('shift_rule_item', sa.Column('day_no', sa.Integer(), nullable=False))
    op.add_column('shift_rule_item', sa.Column('cell_persons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.drop_index(op.f('ix_shift_rule_item_rule_id'), table_name='shift_rule_item')
    op.drop_constraint(op.f('shift_rule_item_rule_id_fkey'), 'shift_rule_item', type_='foreignkey')
    op.create_foreign_key(None, 'shift_rule_item', 'shift_rule_version', ['version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shift_rule_item', 'version')
    op.drop_column('shift_rule_item', 'rule_id')
    op.drop_column('shift_rule_item', 'sequence_no')
    op.drop_column('shift_rule_item', 'shift_code')
    op.drop_column('shift_rule_item', 'repeat_count')
    op.drop_column('shift_rule_item', 'group_type')
    op.drop_column('shift_rule_item', 'remark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_rule_item', sa.Column('remark', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shift_rule_item', sa.Column('group_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('shift_rule_item', sa.Column('repeat_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shift_rule_item', sa.Column('shift_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('shift_rule_item', sa.Column('sequence_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shift_rule_item', sa.Column('rule_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('shift_rule_item', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shift_rule_item', type_='foreignkey')
    op.create_foreign_key(op.f('shift_rule_item_rule_id_fkey'), 'shift_rule_item', 'shift_rule', ['rule_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_shift_rule_item_rule_id'), 'shift_rule_item', ['rule_id'], unique=False)
    op.drop_column('shift_rule_item', 'cell_persons')
    op.drop_column('shift_rule_item', 'day_no')
    op.drop_column('shift_rule_item', 'version_id')
    op.add_column('shift_rule', sa.Column('station_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('shift_rule', sa.Column('rule_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('shift_rule', sa.Column('persons_per_shift', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('shift_rule', 'persons_per_cell')
    op.drop_column('shift_rule', 'start_date')
    op.drop_column('shift_rule', 'cycle_days')
    op.create_index(op.f('ix_schedule_day_schedule_id'), 'schedule_day', ['schedule_id'], unique=False)
    op.add_column('person', sa.Column('rotation_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthly_schedule', sa.Column('year_month', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'monthly_schedule', type_='foreignkey')
    op.drop_index('uq_monthly_schedule_org', table_name='monthly_schedule', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_monthly_schedule_org_month'), 'monthly_schedule', ['org_unit_id', 'year_month'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_column('monthly_schedule', 'rule_version_id')
    op.create_index(op.f('ix_holiday_calendar_year'), 'holiday_calendar', ['year'], unique=False)
    op.drop_table('shift_rule_version')
    # ### end Alembic commands ###
