"""m2_p2_t3_person

Revision ID: cd8a9bd865f0
Revises: 570b6f8a0ab5
Create Date: 2026-07-10 04:41:00.234084
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'cd8a9bd865f0'
down_revision: str | None = '570b6f8a0ab5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('org_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('person_type', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('participate_schedule', sa.Boolean(), nullable=False),
    sa.Column('rotation_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_person_code')
    )
    with op.batch_alter_table('org_unit') as batch_op:
        batch_op.create_foreign_key('fk_org_unit_manager_person', 'person', ['manager_person_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('sys_user') as batch_op:
        batch_op.create_foreign_key('fk_sys_user_person', 'person', ['person_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user') as batch_op:
        batch_op.drop_constraint('fk_sys_user_person', type_='foreignkey')
    with op.batch_alter_table('org_unit') as batch_op:
        batch_op.drop_constraint('fk_org_unit_manager_person', type_='foreignkey')
    op.drop_table('person')
    # ### end Alembic commands ###
